id: I1243871C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:04:29+00:00'
last_modified: '2022-06-07T17:53:02.747426+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD2081
  title: ཆོ་ག་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E70C:
      image_group_id: I4PD2169
      title: ''
      total_pages: 886
      order: 1
      base_file: E70C.txt
    64B8:
      image_group_id: I4PD2170
      title: ''
      total_pages: 812
      order: 2
      base_file: 64B8.txt
    0800:
      image_group_id: I4PD2171
      title: ''
      total_pages: 1034
      order: 3
      base_file: 0800.txt
    '7497':
      image_group_id: I4PD2172
      title: ''
      total_pages: 940
      order: 4
      base_file: 7497.txt
    44DF:
      image_group_id: I4PD2173
      title: ''
      total_pages: 700
      order: 5
      base_file: 44DF.txt
    '2676':
      image_group_id: I4PD2174
      title: ''
      total_pages: 848
      order: 6
      base_file: 2676.txt
    7B47:
      image_group_id: I4PD2175
      title: ''
      total_pages: 1116
      order: 7
      base_file: 7B47.txt
    014A:
      image_group_id: I4PD2176
      title: ''
      total_pages: 696
      order: 8
      base_file: 014A.txt
    758C:
      image_group_id: I4PD2177
      title: ''
      total_pages: 696
      order: 9
      base_file: 758C.txt
    '6434':
      image_group_id: I4PD2178
      title: ''
      total_pages: 866
      order: 10
      base_file: 6434.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
