id: I1243871C
legacy_id: P003143
ocr_import_info:
  bdrc_scan_id: W4PD2081
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T14:57:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:21:55.062820+00:00'
last_modified: 2022-09-04 05:25:16.923178
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD2081
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4PD2081
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོ་ག་ཕྱོགས་བསྒྲིགས།
statistics:
  ocr_word_mean_confidence_index: 0.9188567493927309
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4PD2172:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2172
      total_pages: 940
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4PD2172.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9162182217255685
    legacy_id: v004
  I4PD2173:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2173
      total_pages: 700
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4PD2173.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9337609068978797
    legacy_id: v005
  I4PD2170:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2170
      total_pages: 812
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD2170.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9270416826397486
    legacy_id: v002
  I4PD2171:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2171
      total_pages: 1034
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD2171.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9189299306966197
    legacy_id: v003
  I4PD2176:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2176
      total_pages: 696
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4PD2176.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9333312394503085
    legacy_id: v008
  I4PD2177:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2177
      total_pages: 696
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I4PD2177.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.933192888377566
    legacy_id: v009
  I4PD2175:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2175
      total_pages: 1116
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4PD2175.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9328365041949755
    legacy_id: v007
  I4PD2169:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2169
      total_pages: 886
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD2169.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9269495142296272
    legacy_id: v001
  I4PD2178:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2178
      total_pages: 866
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I4PD2178.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9180245095431724
    legacy_id: v010
  I4PD2174:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2174
      total_pages: 848
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4PD2174.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8612902085887822
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
